# -*- coding: utf-8 -*-
"""dense_reconstruction1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQxiWVfstldu7EqIkPAvVaT-tAAYpsNa
"""

from matplotlib import pyplot as plt
import cv2 as cv
import os
import numpy as np
from google.colab import drive
from google.colab.patches import cv2_imshow

# Load images directly from specified paths
image1 = cv.imread('/content/WhatsApp Image 2024-12-02 at 11.17.40 PM.jpeg')  # Load the first image
image2 = cv.imread('/content/WhatsApp Image 2024-12-02 at 11.18.52 PM.jpeg')  # Load the second image

# Convert images to grayscale for feature extraction
#grayscale_image1 = cv.cvtColor(image1, cv.COLOR_BGR2GRAY)
#grayscale_image2 = cv.cvtColor(image2, cv.COLOR_BGR2GRAY)

# Display the images side by side
plt.figure(figsize=(16, 8))

# Display the first image
plt.subplot(1, 2, 1)  # 1 row, 2 columns, first subplot
plt.imshow(cv.cvtColor(image1, cv.COLOR_BGR2RGB))  # Convert BGR to RGB for correct color display
plt.title('First Image')  # Title for the first image
plt.axis('off')  # Hide the axis

# Display the second image
plt.subplot(1, 2, 2)  # 1 row, 2 columns, second subplot
plt.imshow(cv.cvtColor(image2, cv.COLOR_BGR2RGB))  # Convert BGR to RGB for correct color display
plt.title('Second Image')  # Title for the second image
plt.axis('off')  # Hide the axis

# Show the images
plt.tight_layout()
plt.show()

# Step 1: Detect and match features using SIFT and FLANN
'''it used to detect and describe keypoints in images
where SIFT identifies distinctive points in the image, called keypoints (e.g., corners, blobs)
and SIFT generates descriptors for each keypoint. These are vectors that describe the local image region around the keypoint
 in a way that is invariant to scale, rotation, and some illumination changes.'''
sift = cv.SIFT_create() # Use cv instead of cv2
keypoints1, descriptors1 = sift.detectAndCompute(image1, None)
keypoints2, descriptors2 = sift.detectAndCompute(image2, None)

flann = cv.FlannBasedMatcher(dict(algorithm=1, trees=5), dict(checks=50)) # flann matches descriptors b/w two imges
matches = flann.knnMatch(descriptors1, descriptors2, k=2) #here flann finds  k nearest neighbors for each descriptor. The code uses k=2 to facilitate Lowe's ratio test.
#Specifies that the two closest matches should be returned for each descriptor
# Lowe's ratio test
good_matches = [m for m, n in matches if m.distance < 0.7 * n.distance]
'''m.distance < 0.7 * n.distance: This is the condition for Lowe's ratio test.
The distance of the best match (m.distance) is compared to a fraction (70%) of the distance of the second-best match (n.distance)'''
# Extract corresponding points
pts1 = np.float32([keypoints1[m.queryIdx].pt for m in good_matches])
pts2 = np.float32([keypoints2[m.trainIdx].pt for m in good_matches])
# Draw matches on the images
# Use cv.drawMatches instead of cv2.drawMatches and replace cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS with cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
img_matches = cv.drawMatches(image1, keypoints1, image2, keypoints2, good_matches, None)  #matches are drawn using cv.drawmatches

# Plotting the keypoint matches
plt.figure(figsize=(15, 8))
plt.imshow(img_matches)
plt.title('Keypoint Matches')
plt.show()

import cv2  # Import cv2 for OpenCV functions
import numpy as np  # Import numpy for numerical operations

# Step 2: Compute Fundamental Matrix using OpenCV
F_cv, mask = cv2.findFundamentalMat(pts1, pts2, method=cv2.FM_RANSAC)  # Computes the fundamental matrix F from the point correspondences (pts1, pts2) &
# RANSAC (Random Sample Consensus) is used to make the computation robust to outliers (which is not fit)

# Filter inliers
pts1 = pts1[mask.ravel() == 1]  # Filters pts1 to include only those points corresponding to inliers.
pts2 = pts2[mask.ravel() == 1]

# Normalize the Fundamental Matrix (OpenCV method)
norm_F_cv = F_cv / np.linalg.norm(F_cv)  # Normalize the matrix so that its Frobenius norm is 1

# Step 3: Compute Fundamental Matrix using A-matrix approach (8-point algorithm)
def compute_fundamental_matrix(points1, points2):
    n = len(points1)
    A = np.zeros((n, 9))  # A is an n×9 matrix where n is the number of correspondences.
    # to construct A matrix by taking corresponding points which are (x1,y1) & (x2,y2)
    for i in range(n):
        x1, y1 = points1[i]
        x2, y2 = points2[i]
        A[i] = [x1 * x2, x1 * y2, x1, y1 * x2, y1 * y2, y1, x2, y2, 1]

    # Solve for F using SVD
    U, S, Vt = np.linalg.svd(A)
    F = Vt[-1].reshape(3, 3)  # The last row of Vt (corresponding to the smallest singular value) gives the solution to A

    # Enforce rank-2 constraint
    U, S, Vt = np.linalg.svd(F)  # U, S, Vt: Components of the SVD of F & S: Singular values of F, which indicate its rank
    S[2] = 0  # Setting the smallest singular value (S[2]) to zero reduces the rank of F to 2 [s1, s2, s3] or we are setting the rank as 2 constraint by zeroing out the smallest singular value
    F = U @ np.diag(S) @ Vt  # Rebuild the fundamental matrix F using the modified singular values S. The reconstructed F now has rank 2.

    return F

# Compute fundamental matrix using manual method (to calculate the fundamental matrix F manually from the point correspondences pts1 and pts2.)
F_manual = compute_fundamental_matrix(pts1, pts2)

# Normalize the Fundamental Matrix (Manual method)
norm_F_manual = F_manual / np.linalg.norm(F_manual)  # Normalize the matrix so that its Frobenius norm is 1

# Step 4: Compare both Fundamental Matrices
print("Fundamental Matrix (OpenCV):\n", F_cv)
print("\nNormalized Fundamental Matrix (OpenCV):\n", norm_F_cv)

print("\nFundamental Matrix (Manual):\n", F_manual)
print("\nNormalized Fundamental Matrix (Manual):\n", norm_F_manual)

#Compute Essential matrixE using the intrinsic camera matrix K(contains focal length and principal point information) and the fundamental matrix F(relates points in two images without considering camera intrinsics)

K = np.array([
    [1.55222390e+03, 0.00000000e+00, 1.01531587e+03],
    [0, 1.53599264e+03, 7.63340936e+02],
    [0,   0,   1]
])
'''It contains the internal parameters of the camera,
 which are used to relate image coordinates (in pixels) to camera coordinates (in physical units). This matrix is essential when converting the fundamental matrix F
 into the essential matrix E.'''
#E = K.T @ F @ K
E_cv = K.T @ F_cv @ K #here E_cv: Computed using F_cv where F_cv means Using (OpenCV with RANSAC).
E_manual = K.T @ F_manual @ K #here E_manual Computed using F_manual where F_manual means(Using the A-matrix approach (8-point algorithm).)


print("\nEssential Matrix (OpenCV):\n", E_cv)
print("\nEssential Matrix (Manual):\n", E_manual)

"""K is a 3×3 matrix containing the camera's intrinsic parameters:

K=[
  
    fx 0  cx

    0 fy  cy

    0  0    0]

Where:
fx,fy : Focal lengths in pixels.

 cx,cy: Coordinates of the principal point.
  



"""

#Decompose E into R and t
def decompose_essential_matrix(E):
    U, S, Vt = np.linalg.svd(E)
    W = np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]])

    R1 = U @ W @ Vt
    R2 = U @ W.T @ Vt
    t1 = U[:, 2]
    t2 = -U[:, 2]

    return R1, R2, t1, t2

R1_cv, R2_cv, t1_cv, t2_cv = decompose_essential_matrix(E_cv)
R1_manual, R2_manual, t1_manual, t2_manual = decompose_essential_matrix(E_manual)


print("\nDecomposition of Essential Matrix (OpenCV):")
print("R1:\n",R1_cv)
print("R2:\n",R2_cv)
print("t1:\n",t1_cv)
print("t2:\n",t2_cv)

print("\nDecomposition of Essential Matrix (Manual):")
print("R1:\n",R1_manual)
print("R2:\n",R2_manual)
print("t1:\n",t1_manual)
print("t2:\n",t2_manual)

import matplotlib.pyplot as plt

def draw_epipolar_lines(image1, image2, points1, points2, F):
    """
    Draw epipolar lines on both images.
    Args:
        image1, image2: The input images (BGR format).
        points1, points2: Point correspondences.
        F: Fundamental matrix.
    Returns:
        Two images with epipolar lines drawn.
    """
    # Compute epipolar lines for points in image 2 (lines on image 1)
    lines1 = cv2.computeCorrespondEpilines(points2.reshape(-1, 1, 2), 2, F).reshape(-1, 3)
    # Compute epipolar lines for points in image 1 (lines on image 2)
    lines2 = cv2.computeCorrespondEpilines(points1.reshape(-1, 1, 2), 1, F).reshape(-1, 3)

    img1_color = image1.copy()
    img2_color = image2.copy()

    for r1, r2, pt1, pt2 in zip(lines1, lines2, points1, points2):
        # Random color for each pair
        color = tuple(np.random.randint(0, 255, 3).tolist())

        # Epipolar line on image 1
        x0, y0 = map(int, [0, -r1[2] / r1[1]])
        x1, y1 = map(int, [img1_color.shape[1], -(r1[2] + r1[0] * img1_color.shape[1]) / r1[1]])
        img1_color = cv2.line(img1_color, (x0, y0), (x1, y1), color, 1)
        img1_color = cv2.circle(img1_color, tuple(map(int, pt1)), 5, color, -1)

        # Epipolar line on image 2
        x0, y0 = map(int, [0, -r2[2] / r2[1]])
        x1, y1 = map(int, [img2_color.shape[1], -(r2[2] + r2[0] * img2_color.shape[1]) / r2[1]])
        img2_color = cv2.line(img2_color, (x0, y0), (x1, y1), color, 1)
        img2_color = cv2.circle(img2_color, tuple(map(int, pt2)), 5, color, -1)

    return img1_color, img2_color

# Draw epipolar lines using the corrected function
img1_epilines, img2_epilines = draw_epipolar_lines(image1, image2, pts1, pts2, F_cv)

# Display epipolar lines
plt.figure(figsize=(15, 7))
plt.subplot(121)
plt.title("Epipolar Lines on Image 1")
plt.imshow(cv2.cvtColor(img1_epilines, cv2.COLOR_BGR2RGB))
plt.axis("off")

plt.subplot(122)
plt.title("Epipolar Lines on Image 2")
plt.imshow(cv2.cvtColor(img2_epilines, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.show()

# Step 5: Visualize matches and epipolar lines
def draw_epipolar_lines(image1, image2, points1, points2, F):
    lines1 = cv2.computeCorrespondEpilines(points2.reshape(-1, 1, 2), 2, F).reshape(-1, 3)

    # image1 and image2 are already in color (BGR)
    img1_color = image1.copy() # or image1 if you don't need to preserve the original
    img2_color = image2.copy() # or image2 if you don't need to preserve the original

    image_width = image1.shape[1]
    for pt1, pt2 in zip(points1, points2):
        # Convert points to homogeneous coordinates
        pt2_h = np.array([pt2[0], pt2[1], 1.0])  # Point from img2
        epiline1 = F.T @ pt2_h  # Epipolar line in img1

        # Line equation: ax + by + c = 0
        a, b, c = epiline1

        # Line end points in img1
        x0, y0 = 0, int(-c / b)
        x1, y1 = image_width, int(-(c + a * image_width) / b)

        # Random color for each line
        color = tuple(np.random.randint(0, 255, 3).tolist())

        # Draw line on img1
        img1_color = cv2.line(img1_color, (x0, y0), (x1, y1), color, 1)
        img1_color = cv2.circle(img1_color, tuple(map(int, pt1)), 5, color, -1)

        # Epipolar line for point in img1 (optional)
        pt1_h = np.array([pt1[0], pt1[1], 1.0])  # Point from img1
        epiline2 = F @ pt1_h  # Epipolar line in img2

        # Line equation: ax + by + c = 0
        a, b, c = epiline2

        # Line end points in img2
        x0, y0 = 0, int(-c / b)
        x1, y1 = image_width, int(-(c + a * image_width) / b)

        # Draw line on img2
        img2_color = cv2.line(img2_color, (x0, y0), (x1, y1), color, 1)
        img2_color = cv2.circle(img2_color, tuple(map(int, pt2)), 5, color, -1)

    return img1_color, img2_color

# Use manually computed F_manual
# Visualize epipolar lines using the function
img1_epilines, img2_epilines = draw_epipolar_lines(image1, image2, pts1, pts2, F_manual)

# Display results
plt.figure(figsize=(15, 7))
plt.subplot(121)
plt.title("Epipolar Lines on Image 1 (Manual)")
plt.imshow(cv2.cvtColor(img1_epilines, cv2.COLOR_BGR2RGB))  # Convert BGR to RGB
plt.axis("off")

plt.subplot(122)
plt.title("Epipolar Lines on Image 2 (Manual)")
plt.imshow(cv2.cvtColor(img2_epilines, cv2.COLOR_BGR2RGB))  # Convert BGR to RGB
plt.axis("off")
plt.show()

!pip install open3d

import open3d as o3d

baseline = 0.3  # Baseline in meters

Q = np.array([
    [1, 0, 0, -K[0, 2]],  # Principal point x
    [0, -1, 0, K[1, 2]],  # Principal point y
    [0, 0, 0, K[0, 0]],   # Focal length
    [0, 0, -1 / baseline, 0]
])


print("Q Matrix:")
print(Q)

# Step 6: Compute Disparity Map
def compute_disparity(img1, img2, block_size=3, min_disp=0, num_disp=16*5):
    # Normalize images
    img1 = cv2.normalize(img1, None, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX)
    img2 = cv2.normalize(img2, None, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX)

    stereo = cv2.StereoSGBM_create(
        minDisparity=min_disp,
        numDisparities=num_disp,
        blockSize=block_size,
        P1=8 * 3 * block_size**2,
        P2=32 * 3 * block_size**2,
        disp12MaxDiff=1,
        uniquenessRatio=10,
        speckleWindowSize=100,
        speckleRange=32
    )
    disparity = stereo.compute(image1, image2).astype(np.float32) / 16.0
    return disparity

disparity = compute_disparity(image1, image2)

# Step 8: 3D Reconstruction
def reconstruct_3d(disparity, Q):
    # Q is the re-projection matrix, usually derived from stereo rectification
    points_3d = cv2.reprojectImageTo3D(disparity, Q)
    mask = disparity > disparity.min()
    points_3d = points_3d[mask]
    return points_3d

# Assuming K[0, 0] represents the focal length (fx)
f = K[0, 0]

Q = np.array([
    [1, 0, 0, -image1.shape[1] / 2],
    [0, -1, 0, image1.shape[0] / 2],
    [0, 0, 0, f], # Use the defined f here
    [0, 0, 1 / baseline, 0]
])

points_3d = reconstruct_3d(disparity, Q)

# Visualize Disparity Map
plt.figure(figsize=(10, 5))
plt.title("Disparity Map")
plt.imshow(disparity, cmap='gray')
plt.colorbar()
plt.axis("off")
plt.show()

points_3d = reconstruct_3d(disparity, Q)

# Visualize 3D point cloud
def plot_3d_point_cloud(points_3d, num_points=10000):
    if points_3d.shape[0] > num_points:
        indices = np.random.choice(points_3d.shape[0], num_points, replace=False)
        points_3d = points_3d[indices]
    fig = plt.figure(figsize=(8, 8))
    ax = fig.add_subplot(111, projection='3d')
    x, y, z = points_3d[:, 0], points_3d[:, 1], points_3d[:, 2]
    ax.scatter(x, y, z, s=1, c=z, cmap='jet', marker='.')
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    plt.title("3D Point Cloud")
    plt.show()

plot_3d_point_cloud(points_3d)

